2021-01-15 20:20:33,591 - INFO - Starting bot.....
2021-01-15 20:20:33,699 - INFO - Starting bot engine...
2021-01-15 20:20:33,699 - INFO - Started main loop.
2021-01-17 12:32:48,639 - INFO - Starting bot.....
2021-01-17 12:32:48,756 - INFO - Starting bot engine...
2021-01-17 12:32:48,756 - INFO - Started main loop.
2021-01-17 12:33:09,207 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 77, in start_bot
    if self.check_user_in_db() == None:
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 53, in check_user_in_db
    sql = 'SELECT user_id FROM users_info WHERE user_id = ?' % self.from_id
TypeError: not all arguments converted during string formatting
.
2021-01-17 12:33:09,207 - INFO - Reloading....
2021-01-17 12:33:14,308 - INFO - Starting bot engine...
2021-01-17 12:33:14,321 - INFO - Started main loop.
2021-01-17 12:34:51,947 - INFO - Starting bot.....
2021-01-17 12:34:52,055 - INFO - Starting bot engine...
2021-01-17 12:34:52,058 - INFO - Started main loop.
2021-01-17 12:35:18,794 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 77, in start_bot
    if self.check_user_in_db() == None:
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 53, in check_user_in_db
    sql = 'SELECT user_id FROM users_info WHERE user_id = ?' % self.from_id
TypeError: not all arguments converted during string formatting
.
2021-01-17 12:35:19,296 - INFO - Reloading....
2021-01-17 12:35:30,063 - INFO - Starting bot engine...
2021-01-17 12:35:30,634 - INFO - Started main loop.
2021-01-17 12:35:54,986 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 77, in start_bot
    if self.check_user_in_db() == None:
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 53, in check_user_in_db
    sql = 'SELECT user_id FROM users_info WHERE user_id = ?' % self.from_id
TypeError: not all arguments converted during string formatting
.
2021-01-17 12:35:55,200 - INFO - Reloading....
2021-01-17 12:36:39,840 - INFO - Starting bot.....
2021-01-17 12:36:39,948 - INFO - Starting bot engine...
2021-01-17 12:36:39,950 - INFO - Started main loop.
2021-01-17 12:36:57,520 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 77, in start_bot
    if self.check_user_in_db() == None:
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 53, in check_user_in_db
    sql = 'SELECT user_id FROM users_info WHERE user_id = ?' % self.from_id
TypeError: not all arguments converted during string formatting
.
2021-01-17 12:36:57,684 - INFO - Reloading....
2021-01-17 12:38:19,940 - INFO - Starting bot.....
2021-01-17 12:38:20,049 - INFO - Starting bot engine...
2021-01-17 12:38:20,051 - INFO - Started main loop.
2021-01-17 12:38:44,760 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 77, in start_bot
    if self.check_user_in_db() == None:
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 53, in check_user_in_db
    sql = 'SELECT user_id FROM users_info WHERE user_id = ?' % self.from_id
TypeError: not all arguments converted during string formatting
.
2021-01-17 12:38:45,037 - INFO - Reloading....
2021-01-17 13:04:06,135 - INFO - Starting bot.....
2021-01-17 13:04:06,437 - INFO - Starting bot engine...
2021-01-17 13:04:06,437 - INFO - Started main loop.
2021-01-17 13:04:07,612 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 77, in start_bot
    if self.check_user_in_db() == None:
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 53, in check_user_in_db
    sql = 'SELECT user_id FROM users_info WHERE user_id = ?' % self.from_id
TypeError: not all arguments converted during string formatting
.
2021-01-17 13:04:07,612 - INFO - Reloading....
2021-01-17 13:04:12,709 - INFO - Starting bot engine...
2021-01-17 13:04:12,722 - INFO - Started main loop.
2021-01-17 13:04:48,610 - INFO - Starting bot.....
2021-01-17 13:04:48,710 - INFO - Starting bot engine...
2021-01-17 13:04:48,711 - INFO - Started main loop.
2021-01-17 13:04:51,578 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 77, in start_bot
    if self.check_user_in_db() == False:
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 53, in check_user_in_db
    sql = 'SELECT user_id FROM users_info WHERE user_id = ?' % self.from_id
TypeError: not all arguments converted during string formatting
.
2021-01-17 13:04:51,578 - INFO - Reloading....
2021-01-17 13:04:56,685 - INFO - Starting bot engine...
2021-01-17 13:04:56,686 - INFO - Started main loop.
2021-01-17 13:06:56,546 - INFO - Starting bot.....
2021-01-17 13:06:56,639 - INFO - Starting bot engine...
2021-01-17 13:06:56,639 - INFO - Started main loop.
2021-01-17 13:06:58,843 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 77, in start_bot
    if self.check_user_in_db() is None:
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 53, in check_user_in_db
    sql = 'SELECT user_id FROM users_info WHERE user_id = ?' % self.from_id
TypeError: not all arguments converted during string formatting
.
2021-01-17 13:06:58,843 - INFO - Reloading....
2021-01-17 13:07:03,944 - INFO - Starting bot engine...
2021-01-17 13:07:03,946 - INFO - Started main loop.
2021-01-17 13:09:47,444 - INFO - Starting bot.....
2021-01-17 13:09:47,530 - INFO - Starting bot engine...
2021-01-17 13:09:47,531 - INFO - Started main loop.
2021-01-17 13:09:50,092 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
ValueError: operation parameter must be str
.
2021-01-17 13:09:50,092 - INFO - Reloading....
2021-01-17 13:09:55,183 - INFO - Starting bot engine...
2021-01-17 13:09:55,184 - INFO - Started main loop.
2021-01-17 13:13:07,198 - INFO - Starting bot.....
2021-01-17 13:13:07,302 - INFO - Starting bot engine...
2021-01-17 13:13:07,303 - INFO - Started main loop.
2021-01-17 13:16:20,715 - INFO - Starting bot.....
2021-01-17 13:16:20,822 - INFO - Starting bot engine...
2021-01-17 13:16:20,823 - INFO - Started main loop.
2021-01-17 13:17:00,690 - INFO - Starting bot.....
2021-01-17 13:17:00,801 - INFO - Starting bot engine...
2021-01-17 13:17:00,801 - INFO - Started main loop.
2021-01-17 13:17:02,652 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 58, in add_user_in_db
    sql = "INSERT INTO users_info (user_id, user_name, user_last_name) VALUES (?, ?, ?)" %\
TypeError: not all arguments converted during string formatting
.
2021-01-17 13:17:02,652 - INFO - Reloading....
2021-01-17 13:17:07,748 - INFO - Starting bot engine...
2021-01-17 13:17:07,750 - INFO - Started main loop.
2021-01-17 13:18:19,828 - INFO - Starting bot.....
2021-01-17 13:18:19,941 - INFO - Starting bot engine...
2021-01-17 13:18:19,941 - INFO - Started main loop.
2021-01-17 13:18:23,884 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 58, in add_user_in_db
    sql = "INSERT INTO users_info (user_id, user_name, user_last_name) VALUES (%s, %s, %s)" %\
TypeError: not enough arguments for format string
.
2021-01-17 13:18:23,884 - INFO - Reloading....
2021-01-17 13:18:28,977 - INFO - Starting bot engine...
2021-01-17 13:18:28,979 - INFO - Started main loop.
2021-01-17 13:18:39,012 - INFO - Starting bot.....
2021-01-17 13:18:39,109 - INFO - Starting bot engine...
2021-01-17 13:18:39,109 - INFO - Started main loop.
2021-01-17 13:18:40,877 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 58, in add_user_in_db
    sql = "INSERT INTO users_info (user_id, user_name, user_last_name) VALUES (%d, %s, %s)" %\
TypeError: not enough arguments for format string
.
2021-01-17 13:18:40,877 - INFO - Reloading....
2021-01-17 13:18:45,961 - INFO - Starting bot engine...
2021-01-17 13:18:45,965 - INFO - Started main loop.
2021-01-17 13:18:48,244 - INFO - Starting bot.....
2021-01-17 13:18:48,353 - INFO - Starting bot engine...
2021-01-17 13:18:48,353 - INFO - Started main loop.
2021-01-17 13:18:50,273 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 58, in add_user_in_db
    sql = "INSERT INTO users_info (user_id, user_name, user_last_name) VALUES (%s, %s, %s)" %\
TypeError: not enough arguments for format string
.
2021-01-17 13:18:50,273 - INFO - Reloading....
2021-01-17 13:18:55,362 - INFO - Starting bot engine...
2021-01-17 13:18:55,364 - INFO - Started main loop.
2021-01-17 13:19:30,189 - INFO - Starting bot.....
2021-01-17 13:19:30,282 - INFO - Starting bot engine...
2021-01-17 13:19:30,283 - INFO - Started main loop.
2021-01-17 13:19:31,910 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
TypeError: add_user_in_db() takes 1 positional argument but 2 were given
.
2021-01-17 13:19:31,910 - INFO - Reloading....
2021-01-17 13:19:37,010 - INFO - Starting bot engine...
2021-01-17 13:19:37,012 - INFO - Started main loop.
2021-01-17 13:20:06,354 - INFO - Starting bot.....
2021-01-17 13:20:06,443 - INFO - Starting bot engine...
2021-01-17 13:20:06,443 - INFO - Started main loop.
2021-01-17 13:20:07,832 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
TypeError: add_user_in_db() takes 1 positional argument but 2 were given
.
2021-01-17 13:20:07,832 - INFO - Reloading....
2021-01-17 13:20:12,919 - INFO - Starting bot engine...
2021-01-17 13:20:12,920 - INFO - Started main loop.
2021-01-17 13:20:33,745 - INFO - Starting bot.....
2021-01-17 13:20:33,839 - INFO - Starting bot engine...
2021-01-17 13:20:33,839 - INFO - Started main loop.
2021-01-17 13:20:35,213 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 58, in add_user_in_db
    sql = "INSERT INTO users_info (user_id, user_name, user_last_name) VALUES (%s, %s, %s)" %\
TypeError: not enough arguments for format string
.
2021-01-17 13:20:35,213 - INFO - Reloading....
2021-01-17 13:20:40,311 - INFO - Starting bot engine...
2021-01-17 13:20:40,312 - INFO - Started main loop.
2021-01-17 13:20:44,750 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 58, in add_user_in_db
    sql = "INSERT INTO users_info (user_id, user_name, user_last_name) VALUES (%s, %s, %s)" %\
TypeError: not enough arguments for format string
.
2021-01-17 13:20:44,750 - INFO - Reloading....
2021-01-17 13:20:49,843 - INFO - Starting bot engine...
2021-01-17 13:20:49,845 - INFO - Started main loop.
2021-01-17 13:22:44,669 - INFO - Starting bot.....
2021-01-17 13:22:44,766 - INFO - Starting bot engine...
2021-01-17 13:22:44,766 - INFO - Started main loop.
2021-01-17 13:22:46,846 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 58, in add_user_in_db
    sql = "INSERT INTO users_info (user_id, user_name, user_last_name) VALUES (%d, %s, %s)" %\
TypeError: not enough arguments for format string
.
2021-01-17 13:22:46,846 - INFO - Reloading....
2021-01-17 13:22:51,934 - INFO - Starting bot engine...
2021-01-17 13:22:51,935 - INFO - Started main loop.
2021-01-17 13:23:14,193 - INFO - Starting bot.....
2021-01-17 13:23:14,290 - INFO - Starting bot engine...
2021-01-17 13:23:14,291 - INFO - Started main loop.
2021-01-17 13:23:15,354 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
sqlite3.OperationalError: near "<": syntax error
.
2021-01-17 13:23:15,355 - INFO - Reloading....
2021-01-17 13:23:20,459 - INFO - Starting bot engine...
2021-01-17 13:23:20,460 - INFO - Started main loop.
2021-01-17 13:23:48,892 - INFO - Starting bot.....
2021-01-17 13:23:48,991 - INFO - Starting bot engine...
2021-01-17 13:23:48,992 - INFO - Started main loop.
2021-01-17 13:23:51,267 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
sqlite3.OperationalError: near "<": syntax error
.
2021-01-17 13:23:51,267 - INFO - Reloading....
2021-01-17 13:23:56,343 - INFO - Starting bot engine...
2021-01-17 13:23:56,344 - INFO - Started main loop.
2021-01-17 13:24:07,724 - INFO - Starting bot.....
2021-01-17 13:24:07,823 - INFO - Starting bot engine...
2021-01-17 13:24:07,823 - INFO - Started main loop.
2021-01-17 13:24:08,791 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
sqlite3.OperationalError: near "<": syntax error
.
2021-01-17 13:24:08,791 - INFO - Reloading....
2021-01-17 13:24:13,904 - INFO - Starting bot engine...
2021-01-17 13:24:13,905 - INFO - Started main loop.
2021-01-17 13:26:02,860 - INFO - Starting bot.....
2021-01-17 13:26:02,954 - INFO - Starting bot engine...
2021-01-17 13:26:02,954 - INFO - Started main loop.
2021-01-17 13:26:06,816 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
sqlite3.OperationalError: near "<": syntax error
.
2021-01-17 13:26:06,816 - INFO - Reloading....
2021-01-17 13:26:11,900 - INFO - Starting bot engine...
2021-01-17 13:26:11,902 - INFO - Started main loop.
2021-01-17 13:26:34,376 - INFO - Starting bot.....
2021-01-17 13:26:34,466 - INFO - Starting bot engine...
2021-01-17 13:26:34,466 - INFO - Started main loop.
2021-01-17 13:26:35,978 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 58, in add_user_in_db
    sql = "INSERT INTO users_info (user_id, user_name, user_last_name) VALUES (?, ?, ?)" %\
TypeError: not all arguments converted during string formatting
.
2021-01-17 13:26:35,978 - INFO - Reloading....
2021-01-17 13:26:41,076 - INFO - Starting bot engine...
2021-01-17 13:26:41,077 - INFO - Started main loop.
2021-01-17 13:27:30,678 - INFO - Starting bot.....
2021-01-17 13:27:30,771 - INFO - Starting bot engine...
2021-01-17 13:27:30,771 - INFO - Started main loop.
2021-01-17 13:27:33,920 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
ValueError: operation parameter must be str
.
2021-01-17 13:27:33,920 - INFO - Reloading....
2021-01-17 13:27:39,031 - INFO - Starting bot engine...
2021-01-17 13:27:39,032 - INFO - Started main loop.
2021-01-17 13:28:03,266 - INFO - Starting bot.....
2021-01-17 13:28:03,371 - INFO - Starting bot engine...
2021-01-17 13:28:03,374 - INFO - Started main loop.
2021-01-17 13:28:27,161 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
ValueError: operation parameter must be str
.
2021-01-17 13:28:27,377 - INFO - Reloading....
2021-01-17 13:29:21,690 - INFO - Starting bot.....
2021-01-17 13:29:21,801 - INFO - Starting bot engine...
2021-01-17 13:29:21,801 - INFO - Started main loop.
2021-01-17 13:29:38,761 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 78, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
ValueError: operation parameter must be str
.
2021-01-17 13:29:38,926 - INFO - Reloading....
2021-01-17 13:40:02,388 - INFO - Starting bot.....
2021-01-17 13:40:02,495 - INFO - Starting bot engine...
2021-01-17 13:40:02,496 - INFO - Started main loop.
2021-01-17 13:42:00,405 - INFO - Starting bot.....
2021-01-17 13:42:00,504 - INFO - Starting bot engine...
2021-01-17 13:42:00,504 - INFO - Started main loop.
2021-01-17 13:42:02,785 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 76, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
ValueError: operation parameter must be str
.
2021-01-17 13:42:02,785 - INFO - Reloading....
2021-01-17 13:42:07,876 - INFO - Starting bot engine...
2021-01-17 13:42:07,878 - INFO - Started main loop.
2021-01-17 13:42:16,065 - INFO - Starting bot.....
2021-01-17 13:42:16,163 - INFO - Starting bot engine...
2021-01-17 13:42:16,163 - INFO - Started main loop.
2021-01-17 13:42:18,779 - INFO - Starting bot.....
2021-01-17 13:42:18,892 - INFO - Starting bot engine...
2021-01-17 13:42:18,893 - INFO - Started main loop.
2021-01-17 13:43:52,507 - INFO - Starting bot.....
2021-01-17 13:43:52,619 - INFO - Starting bot engine...
2021-01-17 13:43:52,620 - INFO - Started main loop.
2021-01-17 13:44:11,659 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 76, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
ValueError: operation parameter must be str
.
2021-01-17 13:44:11,844 - INFO - Reloading....
2021-01-17 13:49:31,957 - INFO - Starting bot.....
2021-01-17 13:49:32,057 - INFO - Starting bot engine...
2021-01-17 13:49:32,058 - INFO - Started main loop.
2021-01-17 13:50:02,639 - INFO - Starting bot.....
2021-01-17 13:50:02,745 - INFO - Starting bot engine...
2021-01-17 13:50:02,746 - INFO - Started main loop.
2021-01-17 13:51:57,496 - INFO - Starting bot.....
2021-01-17 13:51:57,600 - INFO - Starting bot engine...
2021-01-17 13:51:57,601 - INFO - Started main loop.
2021-01-17 13:52:29,480 - INFO - Starting bot.....
2021-01-17 13:52:29,578 - INFO - Starting bot engine...
2021-01-17 13:52:29,579 - INFO - Started main loop.
2021-01-17 13:54:21,949 - INFO - Starting bot.....
2021-01-17 13:54:22,051 - INFO - Starting bot engine...
2021-01-17 13:54:22,051 - INFO - Started main loop.
2021-01-17 13:54:59,820 - INFO - Starting bot.....
2021-01-17 13:55:00,015 - INFO - Starting bot engine...
2021-01-17 13:55:00,016 - INFO - Started main loop.
2021-01-17 13:55:21,949 - ERROR - Error type in BOT.PY file -     Traceback (most recent call last):
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 77, in start_bot
    self.add_user_in_db(self.from_id)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\bot.py", line 60, in add_user_in_db
    self.db.query(sql)
  File "C:\Users\kapitazzz\PycharmProjects\bot_for_vk\database.py", line 21, in query
    self.cursor.execute(cmd)
ValueError: operation parameter must be str
.
2021-01-17 13:55:22,124 - INFO - Reloading....
